CREATE TABLE weatherview.Philadelphia (
  WEATHER_MAIN VARCHAR(255) NOT NULL,
  WEATHER_DESCRIPTION VARCHAR(255) NOT NULL,
  RAIN FLOAT DEFAULT NULL,
  SNOW FLOAT DEFAULT NULL,
  TEMPERATURE FLOAT NOT NULL,
  PRESSURE FLOAT NOT NULL,
  HUMIDITY FLOAT NOT NULL,
  VISIBILITY FLOAT NOT NULL,
  WIND_SPEED FLOAT NOT NULL,
  WIND_GUST FLOAT NOT NULL,
  CLOUD_COVER FLOAT NOT NULL,
  RECORD_DATE DATETIME NOT NULL,
  PRIMARY KEY (RECORD_DATE)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
COMMENT = 'Weather for Philadelphia, PA 19104';
