CREATE TABLE weatherview.Philadelphia (
  WEATHER_MAIN VARCHAR(255) DEFAULT NULL,
  WEATHER_DESCRIPTION VARCHAR(255) DEFAULT NULL,
  TEMPERATURE FLOAT DEFAULT NULL,
  PRESSURE FLOAT DEFAULT NULL,
  HUMIDITY FLOAT DEFAULT NULL,
  VISIBILITY FLOAT DEFAULT NULL,
  WIND_SPEED FLOAT DEFAULT NULL,
  WIND_GUST FLOAT DEFAULT NULL,
  CLOUD_COVER FLOAT DEFAULT NULL,
  RECORD_DATE DATETIME NOT NULL,
  PRIMARY KEY (RECORD_DATE)
)
ENGINE = INNODB,
COMMENT = 'Weather for Philadelphia, PA 19104';
