CREATE TABLE Trolley.ROUTE_10 (
  LATITUDE FLOAT NOT NULL,
  LONGITUDE FLOAT NOT NULL,
  TRIP_ID INT(8) NOT NULL,
  VEHICLE_ID INT(6) NOT NULL,
  DIRECTION VARCHAR(255) DEFAULT NULL,
  DESTINATION VARCHAR(255) DEFAULT NULL,
  LATE INT(3) NOT NULL,
  RECORD_DATE DATETIME NOT NULL,
  PRIMARY KEY (RECORD_DATE, TRIP_ID)
)
ENGINE = INNODB;

CREATE TABLE Trolley.ROUTE_11 (
  LATITUDE FLOAT NOT NULL,
  LONGITUDE FLOAT NOT NULL,
  TRIP_ID INT(8) NOT NULL,
  VEHICLE_ID INT(6) NOT NULL,
  DIRECTION VARCHAR(255) DEFAULT NULL,
  DESTINATION VARCHAR(255) DEFAULT NULL,
  LATE INT(3) NOT NULL,
  RECORD_DATE DATETIME NOT NULL,
  PRIMARY KEY (RECORD_DATE, TRIP_ID)
)
ENGINE = INNODB;

CREATE TABLE Trolley.ROUTE_13 (
  LATITUDE FLOAT NOT NULL,
  LONGITUDE FLOAT NOT NULL,
  TRIP_ID INT(8) NOT NULL,
  VEHICLE_ID INT(6) NOT NULL,
  DIRECTION VARCHAR(255) DEFAULT NULL,
  DESTINATION VARCHAR(255) DEFAULT NULL,
  LATE INT(3) NOT NULL,
  RECORD_DATE DATETIME NOT NULL,
  PRIMARY KEY (RECORD_DATE, TRIP_ID)
)
ENGINE = INNODB;

CREATE TABLE Trolley.ROUTE_15 (
  LATITUDE FLOAT NOT NULL,
  LONGITUDE FLOAT NOT NULL,
  TRIP_ID INT(8) NOT NULL,
  VEHICLE_ID INT(6) NOT NULL,
  DIRECTION VARCHAR(255) DEFAULT NULL,
  DESTINATION VARCHAR(255) DEFAULT NULL,
  LATE INT(3) NOT NULL,
  RECORD_DATE DATETIME NOT NULL,
  PRIMARY KEY (RECORD_DATE, TRIP_ID)
)
ENGINE = INNODB;

CREATE TABLE Trolley.ROUTE_34 (
  LATITUDE FLOAT NOT NULL,
  LONGITUDE FLOAT NOT NULL,
  TRIP_ID INT(8) NOT NULL,
  VEHICLE_ID INT(6) NOT NULL,
  DIRECTION VARCHAR(255) DEFAULT NULL,
  DESTINATION VARCHAR(255) DEFAULT NULL,
  LATE INT(3) NOT NULL,
  RECORD_DATE DATETIME NOT NULL,
  PRIMARY KEY (RECORD_DATE, TRIP_ID)
)
ENGINE = INNODB;

CREATE TABLE Trolley.ROUTE_36 (
  LATITUDE FLOAT NOT NULL,
  LONGITUDE FLOAT NOT NULL,
  TRIP_ID INT(8) NOT NULL,
  VEHICLE_ID INT(6) NOT NULL,
  DIRECTION VARCHAR(255) DEFAULT NULL,
  DESTINATION VARCHAR(255) DEFAULT NULL,
  LATE INT(3) NOT NULL,
  RECORD_DATE DATETIME NOT NULL,
  PRIMARY KEY (RECORD_DATE, TRIP_ID)
)
ENGINE = INNODB;

CREATE TABLE Trolley.ROUTE_101 (
  LATITUDE FLOAT NOT NULL,
  LONGITUDE FLOAT NOT NULL,
  TRIP_ID INT(8) NOT NULL,
  VEHICLE_ID INT(6) NOT NULL,
  DIRECTION VARCHAR(255) DEFAULT NULL,
  DESTINATION VARCHAR(255) DEFAULT NULL,
  LATE INT(3) NOT NULL,
  RECORD_DATE DATETIME NOT NULL,
  PRIMARY KEY (RECORD_DATE, TRIP_ID)
)
ENGINE = INNODB;

CREATE TABLE Trolley.ROUTE_102 (
  LATITUDE FLOAT NOT NULL,
  LONGITUDE FLOAT NOT NULL,
  TRIP_ID INT(8) NOT NULL,
  VEHICLE_ID INT(6) NOT NULL,
  DIRECTION VARCHAR(255) DEFAULT NULL,
  DESTINATION VARCHAR(255) DEFAULT NULL,
  LATE INT(3) NOT NULL,
  RECORD_DATE DATETIME NOT NULL,
  PRIMARY KEY (RECORD_DATE, TRIP_ID)
)
ENGINE = INNODB;
