#!/bin/bash
# author: John Zlotek
# usage: installing python3 virtual environment with packages

command -v pip >/dev/null || (echo "Need to have pip installed" && exit 1)
command -v virtualenv >/dev/null || pip install virtualenv --user

virtualenv ./venv --python python3 || if [[ $(python --version | egrep '\s3' | wc -l) -eq 1 ]]; then
  virtualenv ./venv --python python
else
  echo "Please install Python 3"
  exit 1
fi

ACTIVATE_LOC="$(find ./venv -type f -name activate)"

source "$ACTIVATE_LOC"

if [[ -f requirements.txt ]]; then
  pip install -r requirements.txt
fi

echo "Done installing"
echo "Run \`source $ACTIVATE_LOC\` to enter the virtual environment"

